# Generated by Django 5.0.5 on 2025-04-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Worker', 'Worker'), ('Ambassador', 'Ambassador')], default='Worker', max_length=50),
        ),
    ]
