# Generated by Django 5.1.7 on 2025-04-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Worker', 'Worker'), ('Ambassador', 'Ambassador')], max_length=50),
        ),
    ]
