
# Generated by Django 5.1.7 on 2025-04-10 11:39
# Generated by Django 5.0.5 on 2025-04-07 22:47
# 83054005a7a4cef253d219ed271d224c9ffcacc6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Worker', 'Worker'), ('Ambassador', 'Ambassador')], max_length=50),
        ),
    ]
