# Generated by Django 5.1.7 on 2025-04-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='category',
        ),
        migrations.AddField(
            model_name='job',
            name='contact',
            field=models.CharField(default='o712345678', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateTimeField(),
        ),
    ]
